export type FiltersType = {
  query?: string;
  name?: string;
  model?: string;
  priceRange?: { min?: number; max?: number };
  minimumRentalDays?: number;
  depositRange?: { min?: number; max?: number };
  passengers?: number;
  luggage?: number;
  chassisType?: string;
  optionType?: string;
  transmission?: string;
  cruiseControl?: boolean;
  hillStartAssist?: boolean;
  appleCarplay?: boolean;
  seatHeating?: boolean;
  seatCooling?: boolean;
  airConditioning?: boolean;
  rearSensor?: boolean;
  audioSystem?: string;
  monitor?: string;
  driverSeatAdjustment?: string;
  panoramicRoof?: boolean;
  gps?: boolean;
  connectivity?: string[];
  brakingSystem?: string[];
  autoPark?: boolean;
  autoDrive?: boolean;
  engine?: {
    type?: string;
    capacity?: number;
    cylinders?: number;
    acceleration?: number;
    fuelConsumption?: number;
  };
  accelerationRange?: { min: number; max: number };
  fuelConsumptionRange?: { min: number; max: number };
  with_driver?: string;
  sortType?: string;
  location?: string;
};
